---
- name: create resources to build a VM
  hosts: localhost
  collections:
   - azure.azcollection
  vars:
    user_id: test-account
    user_principal_name: ed
    object_id: 87677
  tasks:

  - name: Create user
    azure_rm_aduser:
      user_principal_name: "{{ user_id }}"
      state: "present"
      account_enabled: "True"
      display_name: "Test_{{ user_principal_name }}_Display_Name"
      password_profile: "password"
      mail_nickname: "Test_{{ user_principal_name }}_mail_nickname"
      on_premises_immutable_id: "{{ object_id }}"
      given_name: "First"
      surname: "Last"
      user_type: "Member"
      usage_location: "US"
      mail: "{{ user_principal_name }}@contoso.com"
      mobile_phone: "+1234567890123"
      company_name: 'Test Company'
      on_premises_extension_attributes:
        extension_attribute1: "test_extension_attribute1"
        extension_attribute2: "test_extension_attribute2"
        extension_attribute11: "test_extension_attribute11"
