# AWS playbook
---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: AWX_KEY             # Key used for SSH
    region: use2-az1       # Region may affect response and pricing
    image: ami-0c80e2b6ccb9ad6d1 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "example testing"
    instance_type: t2.nano       # Choose instance type, check AWS for pricing
    # vpc_id: subnet-012345
    sec_group: "test-security-group"

  tasks:
- name: start an instance and Add EBS
  amazon.aws.ec2_instance:
    name: "Awx-test-instance"
    vpc_subnet_id: subnet-5ca1ab1e
    instance_type: "{{ instance_type }}"
    key_name: " {{ key_name }}"
    security_group: "{{ sec_group }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 16
          delete_on_termination: true
