# AWS playbook
---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: "{{ lookup('env', 'AWX_KEY') }}"    # Key used for SSH
    region: use2-az1       # Region may affect response and pricing
    image: ami-0c80e2b6ccb9ad6d1 # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "example testing"
    instance_type: t2.nano       # Choose instance type, check AWS for pricing
    # vpc_id: subnet-012345
    sec_group: "test-security-group"

  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "test-awx-server"
      key_name: "{{ key_name }}"
      vpc_subnet_id: subnet-5ca1ab1e
      instance_type: "{{ instance_type }}"
      security_group: "{{ sec_group }}"
      network_interfaces:
        - assign_public_ip: true
      image_id: "{{ image }}"
      tags:
        Environment: Testing

