---
- name: get service state
  hosts: localhost
  become: yes

  tasks:
    - name: Get uptime information
      shell: /usr/bin/uptime
      register: result
    - name: Print return information from the previous task
      debug:
        var: result
        verbosity: 2
