---
- name: get service state
  hosts: Windows_node1

  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ ansible_facts | to_nice_yaml }}
