- name: Windoows ping
  hosts: Windows_node1
  vars:
    test_url1: "https://{{ ansible_hostname }}/Tthis.is.theurl.butlon.asmx"
    test_url2: "https://{{ ansible_host }}/Tthis.is.theurl.butlon.asmx"
    test_url3: "https://{{ inventory_hostname }}/Tthis.is.theurl.butlon.asmx"
  tasks:
    - name: Print the gateway for each host when defined
      win_ping:
    - debug: var: test_url1
    - debug: var: test_url2
    - debug: var: test_url3
    
