---
- name: get service state
  hosts: Windows_node1

  tasks:
    # - name: Print the gateway for each host when defined
    #   ansible.builtin.debug:
    #     msg: System {{ ansible_facts | to_nice_yaml }}
    - name: Create directory structure
      win_file:
        path: C:\Temp\
        state: directory
    - name: Download 7zip to specified path
      win_get_url:
        url: https://www.7-zip.org/a/7z2409-arm64.exe
        dest: C:\temp\7z.exe
    - name: Install 7zip and use a file version for the installation check
      win_package:
        path: C:\Temp\7z.exe
        arguments: /S

